# Generated by Django 2.0 on 2021-08-13 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210813_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
