# Generated by Django 3.2.6 on 2021-08-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210813_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project'),
        ),
    ]
